from ghcr.io/8clever/betacall_v2/system:main as build
arg project
arg base_url
env BASE_URL=$base_url
copy . .
run npm ci --legacy-peer-deps
run npx nx build $project

from steebchen/nginx-spa:stable
arg project
arg base_url
copy --from=build /app/dist/packages/$project /app$base_url
copy --from=build /app/dist/packages/$project/index.html /app/index.html