from ghcr.io/8clever/betacall_v2/system:main as build
copy . .
ARG project
run npm ci --legacy-peer-deps
run npx nx build $project

from node:gallium-alpine
workdir /app
ARG project
copy --from=build /app/dist/packages/$project .
copy --from=build /app/node_modules ./node_modules
cmd node main