from ghcr.io/8clever/betacall_v2/system:main as build
copy . .
ARG PROJECT
run npm ci --legacy-peer-deps
run npx nx build $PROJECT

from node:gallium-alpine
workdir /app
ARG PROJECT
ARG DIST=/app/dist/packages/$PROJECT
copy --from=build ${DIST}
copy --from=build /app/node_modules ./node_modules
cmd node main