from ghcr.io/8clever/betacall_v2/system:main as build
arg project
arg base-url
env BASE_URL=$base-url
copy . .
run npm ci --legacy-peer-deps
run npx nx build $project

from steebchen/nginx-spa:stable
arg project
copy --from=build /app/dist/packages/$project /app